/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.Test;
import Controller.App;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App sut = new App();
        
    }
}
